# Generated by Django 5.2.4 on 2025-08-02 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('budget_range', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('page_url', models.TextField(blank=True, null=True)),
                ('event_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('feature_id', models.CharField(max_length=100)),
                ('feature_name', models.CharField(max_length=255)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.featuresubmission')),
            ],
        ),
    ]
